# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FDF_Main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SearchDirectory_ADD = QtWidgets.QPushButton(self.centralwidget)
        self.SearchDirectory_ADD.setMaximumSize(QtCore.QSize(20, 16777215))
        self.SearchDirectory_ADD.setObjectName("SearchDirectory_ADD")
        self.verticalLayout_3.addWidget(self.SearchDirectory_ADD)
        self.SearchDirectory_DEL = QtWidgets.QPushButton(self.centralwidget)
        self.SearchDirectory_DEL.setMaximumSize(QtCore.QSize(20, 16777215))
        self.SearchDirectory_DEL.setObjectName("SearchDirectory_DEL")
        self.verticalLayout_3.addWidget(self.SearchDirectory_DEL)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.SearchDirectoryList = QtWidgets.QListWidget(self.centralwidget)
        self.SearchDirectoryList.setObjectName("SearchDirectoryList")
        self.horizontalLayout.addWidget(self.SearchDirectoryList)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PreserveDirectory_ADD = QtWidgets.QPushButton(self.centralwidget)
        self.PreserveDirectory_ADD.setMaximumSize(QtCore.QSize(20, 16777215))
        self.PreserveDirectory_ADD.setObjectName("PreserveDirectory_ADD")
        self.verticalLayout_2.addWidget(self.PreserveDirectory_ADD)
        self.PreserveDirectory_DEL = QtWidgets.QPushButton(self.centralwidget)
        self.PreserveDirectory_DEL.setMaximumSize(QtCore.QSize(20, 16777215))
        self.PreserveDirectory_DEL.setObjectName("PreserveDirectory_DEL")
        self.verticalLayout_2.addWidget(self.PreserveDirectory_DEL)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.PreserveDirectoryList = QtWidgets.QListWidget(self.centralwidget)
        self.PreserveDirectoryList.setObjectName("PreserveDirectoryList")
        self.horizontalLayout_2.addWidget(self.PreserveDirectoryList)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Databasefile = QtWidgets.QLineEdit(self.centralwidget)
        self.Databasefile.setText("")
        self.Databasefile.setObjectName("Databasefile")
        self.horizontalLayout_7.addWidget(self.Databasefile)
        self.Databasefile_Elipsis = QtWidgets.QPushButton(self.centralwidget)
        self.Databasefile_Elipsis.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Databasefile_Elipsis.setObjectName("Databasefile_Elipsis")
        self.horizontalLayout_7.addWidget(self.Databasefile_Elipsis)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Configurationfile = QtWidgets.QLineEdit(self.centralwidget)
        self.Configurationfile.setObjectName("Configurationfile")
        self.horizontalLayout_8.addWidget(self.Configurationfile)
        self.Configurationfile_Elipsis = QtWidgets.QPushButton(self.centralwidget)
        self.Configurationfile_Elipsis.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Configurationfile_Elipsis.setObjectName("Configurationfile_Elipsis")
        self.horizontalLayout_8.addWidget(self.Configurationfile_Elipsis)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Outputscript = QtWidgets.QLineEdit(self.centralwidget)
        self.Outputscript.setObjectName("Outputscript")
        self.horizontalLayout_9.addWidget(self.Outputscript)
        self.Outputscript_Elipsis = QtWidgets.QPushButton(self.centralwidget)
        self.Outputscript_Elipsis.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Outputscript_Elipsis.setObjectName("Outputscript_Elipsis")
        self.horizontalLayout_9.addWidget(self.Outputscript_Elipsis)
        self.gridLayout.addLayout(self.horizontalLayout_9, 4, 1, 1, 1)
        self.StartProcessing = QtWidgets.QPushButton(self.centralwidget)
        self.StartProcessing.setObjectName("StartProcessing")
        self.gridLayout.addWidget(self.StartProcessing, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit_Configuration_File = QtWidgets.QAction(MainWindow)
        self.actionEdit_Configuration_File.setObjectName("actionEdit_Configuration_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLoad_Configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionSave_Configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_Configuration.setObjectName("actionSave_Configuration")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Configuration)
        self.menuFile.addAction(self.actionSave_Configuration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label.setBuddy(self.SearchDirectoryList)
        self.label_2.setBuddy(self.PreserveDirectoryList)
        self.label_3.setBuddy(self.Databasefile)
        self.label_4.setBuddy(self.Configurationfile)
        self.label_5.setBuddy(self.Outputscript)

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SearchDirectory_ADD, self.SearchDirectory_DEL)
        MainWindow.setTabOrder(self.SearchDirectory_DEL, self.PreserveDirectory_ADD)
        MainWindow.setTabOrder(self.PreserveDirectory_ADD, self.PreserveDirectory_DEL)
        MainWindow.setTabOrder(self.PreserveDirectory_DEL, self.PreserveDirectoryList)
        MainWindow.setTabOrder(self.PreserveDirectoryList, self.SearchDirectoryList)
        MainWindow.setTabOrder(self.SearchDirectoryList, self.Configurationfile)
        MainWindow.setTabOrder(self.Configurationfile, self.Outputscript)
        MainWindow.setTabOrder(self.Outputscript, self.StartProcessing)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fast Duplicate Finder"))
        self.label.setText(_translate("MainWindow", "Search these directories:"))
        self.SearchDirectory_ADD.setText(_translate("MainWindow", "+"))
        self.SearchDirectory_DEL.setText(_translate("MainWindow", "-"))
        self.SearchDirectoryList.setToolTip(_translate("MainWindow", "Locate duplicate files in these directories..."))
        self.label_2.setText(_translate("MainWindow", "But don\'t delete from these directories:"))
        self.PreserveDirectory_ADD.setText(_translate("MainWindow", "+"))
        self.PreserveDirectory_DEL.setText(_translate("MainWindow", "-"))
        self.PreserveDirectoryList.setToolTip(_translate("MainWindow", "Dont delete files from these directories..."))
        self.label_3.setText(_translate("MainWindow", "&Database File:"))
        self.Databasefile.setToolTip(_translate("MainWindow", "Save information in this file so deduplicating the same directories in future will be faster..."))
        self.Databasefile_Elipsis.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Confi&guration File:"))
        self.Configurationfile.setToolTip(_translate("MainWindow", "Use configuration information in this file, so you don\'t have to keep entering the same information..."))
        self.Configurationfile_Elipsis.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "O&utput script file:"))
        self.Outputscript.setToolTip(_translate("MainWindow", "Create a script file with deletion commands and other information with this name (default fdf_scanner_output.bat or .sh depending on OS)"))
        self.Outputscript_Elipsis.setText(_translate("MainWindow", "..."))
        self.StartProcessing.setToolTip(_translate("MainWindow", "Locate duplicates and create output script..."))
        self.StartProcessing.setText(_translate("MainWindow", "Find duplicates and create output script"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionEdit_Configuration_File.setText(_translate("MainWindow", "&Edit Configuration File"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionLoad_Configuration.setText(_translate("MainWindow", "Load Configuration"))
        self.actionSave_Configuration.setText(_translate("MainWindow", "Save Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

